/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cmjd107.librarymanagement.view;

import cmjd107.librarymanagement.controller.BookController;
import cmjd107.librarymanagement.controller.BurrowingController;
import cmjd107.librarymanagement.controller.MemberController;
import cmjd107.librarymanagement.dto.BookDto;
import cmjd107.librarymanagement.dto.BurrowingDetailDto;
import cmjd107.librarymanagement.dto.BurrowingDto;
import cmjd107.librarymanagement.dto.MemberDto;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class BurrowingView extends javax.swing.JPanel {

    private final BookController BOOK_CONTROLLER;
    private final MemberController MEMBER_CONTROLLER;
    private final BurrowingController BURROWING_CONTROLLER;
    private ArrayList<BurrowingDetailDto> burrowingDetailDtos = new ArrayList<>();

    /**
     * Creates new form MemberView
     */
    public BurrowingView() {
        BOOK_CONTROLLER = new BookController();
        MEMBER_CONTROLLER = new MemberController();
        BURROWING_CONTROLLER = new BurrowingController();
        initComponents();
        loadCmbBookId();
        loadCmbMemberId();
        loadBurrowingId();
        loadTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtBurrowingId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBurrowingView = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        cmbBookId = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbMemberId = new javax.swing.JComboBox<>();
        lblBookDetails = new javax.swing.JLabel();
        lblMemberDetails = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        btnBurrow = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Book Burrowing"));
        setPreferredSize(new java.awt.Dimension(992, 2));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Burrowing Id");

        txtBurrowingId.setEditable(false);
        txtBurrowingId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Book Id");

        tblBurrowingView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBurrowingView);

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        cmbBookId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBookIdActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Member Id");

        cmbMemberId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMemberId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMemberIdActionPerformed(evt);
            }
        });

        lblBookDetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBookDetails.setForeground(new java.awt.Color(255, 0, 0));
        lblBookDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblMemberDetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMemberDetails.setForeground(new java.awt.Color(255, 0, 0));
        lblMemberDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Qty");

        txtQty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnBurrow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBurrow.setText("Burrow");
        btnBurrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBurrowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBurrowingId, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblMemberDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBookDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 56, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBurrow, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBurrow, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBurrowingId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMemberDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBookDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addToTable();
    }//GEN-LAST:event_btnAddActionPerformed

    private void cmbBookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBookIdActionPerformed
        loadSelectedBook();
    }//GEN-LAST:event_cmbBookIdActionPerformed

    private void cmbMemberIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMemberIdActionPerformed
        loadSelectedMember();
    }//GEN-LAST:event_cmbMemberIdActionPerformed

    private void btnBurrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBurrowActionPerformed
        burrowBooks();
    }//GEN-LAST:event_btnBurrowActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBurrow;
    private javax.swing.JComboBox<String> cmbBookId;
    private javax.swing.JComboBox<String> cmbMemberId;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBookDetails;
    private javax.swing.JLabel lblMemberDetails;
    private javax.swing.JTable tblBurrowingView;
    private javax.swing.JTextField txtBurrowingId;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables

    private void loadCmbBookId() {
        try {
            ArrayList<BookDto> bookDtos = BOOK_CONTROLLER.getAllBooks();
            cmbBookId.removeAllItems();
            cmbBookId.addItem("");
            for (BookDto bookDto : bookDtos) {
                cmbBookId.addItem(bookDto.getBookId());
            }
        } catch (Exception ex) {
            Logger.getLogger(BurrowingView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadCmbMemberId() {
        try {
            ArrayList<MemberDto> memberDtos = MEMBER_CONTROLLER.getAllMembers();
            cmbMemberId.removeAllItems();
            cmbMemberId.addItem("");
            for (MemberDto memberDto : memberDtos) {
                cmbMemberId.addItem(memberDto.getMembetId());
            }
        } catch (Exception ex) {
            Logger.getLogger(BurrowingView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadSelectedBook() {
        try {
            String bookId = (String) cmbBookId.getSelectedItem();
            BookDto bookDto = BOOK_CONTROLLER.getBookById(bookId);
            if (bookDto != null) {
                lblBookDetails.setText(bookDto.getCategoryId() + " | " + bookDto.getTitle() + " | " + bookDto.getAuthor() + " | " + bookDto.getQty());
            }
        } catch (Exception ex) {
            Logger.getLogger(BurrowingView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadSelectedMember() {
        try {
            String memberId = (String) cmbMemberId.getSelectedItem();
            MemberDto memberDto = MEMBER_CONTROLLER.getMemberbyId(memberId);
            if (memberDto != null) {
                lblMemberDetails.setText(memberDto.getName() + " | " + memberDto.getAddress() + " | " + memberDto.getContactNumber());
            }
        } catch (Exception ex) {
            Logger.getLogger(BurrowingView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadBurrowingId() {
        try {
            String latestId = BURROWING_CONTROLLER.getLatestId();
            if (latestId == null) {
                txtBurrowingId.setText("BU001");
            } else {
                int idNum = Integer.parseInt(latestId.substring(2));
                idNum++;
                String newId = String.format("BU%03d", idNum);
                txtBurrowingId.setText(newId);
            }
        } catch (Exception ex) {
            Logger.getLogger(BurrowingView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void addToTable() {
        try {
            BurrowingDetailDto burrowingDetailDto = new BurrowingDetailDto();

            LocalDate currentDate = LocalDate.now();
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDate dueDate = currentDate.plusDays(7);

            BookDto bookDto = BOOK_CONTROLLER.getBookById((String) cmbBookId.getSelectedItem());
            if (Integer.parseInt(txtQty.getText()) <= bookDto.getQty()) {
                burrowingDetailDto.setBookId((String) cmbBookId.getSelectedItem());
                burrowingDetailDto.setQty(Integer.parseInt(txtQty.getText()));
                burrowingDetailDto.setDueDate(dueDate.format(dtf));
                burrowingDetailDto.setIsReturned(false);
                burrowingDetailDtos.add(burrowingDetailDto);

                Object[] rowData = {burrowingDetailDto.getBookId(), burrowingDetailDto.getQty(), burrowingDetailDto.getDueDate()};
                DefaultTableModel dtm = (DefaultTableModel) tblBurrowingView.getModel();
                dtm.addRow(rowData);
                clearBook();
                cmbMemberId.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "There are only " + bookDto.getQty() + " books left. You cannot Exeed");
                clearBook();
            }

        } catch (Exception ex) {
            Logger.getLogger(BurrowingView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadTable() {
        String[] columns = {"BookId", "Qty", "Due Date"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblBurrowingView.setModel(dtm);
    }

    private void clearBook() {
        cmbBookId.setSelectedIndex(0);
        lblBookDetails.setText("");
        txtQty.setText("");
    }

    private void burrowBooks() {
        try {
            BurrowingDto burrowingDto = new BurrowingDto();
            burrowingDto.setBurrowingId(txtBurrowingId.getText());
            burrowingDto.setMemberId((String) cmbMemberId.getSelectedItem());

            LocalDate currentDate = LocalDate.now();
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String date = currentDate.format(dtf);
            burrowingDto.setBurrowDate(date);

            burrowingDto.setBurrowingDetailDtos(burrowingDetailDtos);

            String resp = BURROWING_CONTROLLER.makeBurrowing(burrowingDto);
            JOptionPane.showMessageDialog(this, resp);
            clearForm();
            cmbMemberId.setEnabled(true);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void clearForm() {
        cmbMemberId.setSelectedIndex(0);
        lblMemberDetails.setText("");
        clearBook();
        loadBurrowingId();
        DefaultTableModel dtm = (DefaultTableModel) tblBurrowingView.getModel();
        int rowCount = tblBurrowingView.getRowCount();
        for (int i = rowCount - 1 ; i >=0 ; i--) {
            dtm.removeRow(i);
        }
    }

}
