/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cmjd107.librarymanagement.view;

import cmjd107.librarymanagement.controller.BookController;
import cmjd107.librarymanagement.controller.BurrowingController;
import cmjd107.librarymanagement.controller.MemberController;
import cmjd107.librarymanagement.dto.BookDto;
import cmjd107.librarymanagement.dto.MemberDto;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class BurrowingView extends javax.swing.JPanel {

    private final BookController BOOK_CONTROLLER;
    private final MemberController MEMBER_CONTROLLER;
    private final BurrowingController BURROWING_CONTROLLER;

    /**
     * Creates new form MemberView
     */
    public BurrowingView() {
        BOOK_CONTROLLER = new BookController();
        MEMBER_CONTROLLER = new MemberController();
        BURROWING_CONTROLLER = new BurrowingController();
        initComponents();
        loadCmbBookId();
        loadCmbMemberId();
        loadBurrowingId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtBurrowingId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReturns = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        cmbBookId = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbMemberId = new javax.swing.JComboBox<>();
        lblBookDetails = new javax.swing.JLabel();
        lblMemberDetails = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        btnBurrow = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Book Burrowing"));
        setPreferredSize(new java.awt.Dimension(992, 2));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Burrowing Id");

        txtBurrowingId.setEditable(false);
        txtBurrowingId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Book Id");

        tblReturns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReturns);

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        cmbBookId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBookIdActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Member Id");

        cmbMemberId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMemberId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMemberIdActionPerformed(evt);
            }
        });

        lblBookDetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBookDetails.setForeground(new java.awt.Color(255, 0, 0));
        lblBookDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblMemberDetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMemberDetails.setForeground(new java.awt.Color(255, 0, 0));
        lblMemberDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Qty");

        txtQty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnBurrow.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBurrow.setText("Burrow");
        btnBurrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBurrowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBurrowingId))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblBookDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblMemberDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQty)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBurrow, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBurrowingId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBookDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMemberDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnBurrow, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

    }//GEN-LAST:event_btnAddActionPerformed

    private void cmbBookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBookIdActionPerformed
        loadSelectedBook();
    }//GEN-LAST:event_cmbBookIdActionPerformed

    private void cmbMemberIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMemberIdActionPerformed
        loadSelectedMember();
    }//GEN-LAST:event_cmbMemberIdActionPerformed

    private void btnBurrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBurrowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBurrowActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBurrow;
    private javax.swing.JComboBox<String> cmbBookId;
    private javax.swing.JComboBox<String> cmbMemberId;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBookDetails;
    private javax.swing.JLabel lblMemberDetails;
    private javax.swing.JTable tblReturns;
    private javax.swing.JTextField txtBurrowingId;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables

    private void loadCmbBookId() {
        try {
            ArrayList<BookDto> bookDtos = BOOK_CONTROLLER.getAllBooks();
            cmbBookId.removeAllItems();
            cmbBookId.addItem("");
            for (BookDto bookDto : bookDtos) {
                cmbBookId.addItem(bookDto.getBookId());
            }
        } catch (Exception ex) {
            Logger.getLogger(BurrowingView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadCmbMemberId() {
        try {
            ArrayList<MemberDto> memberDtos = MEMBER_CONTROLLER.getAllMembers();
            cmbMemberId.removeAllItems();
            cmbMemberId.addItem("");
            for (MemberDto memberDto : memberDtos) {
                cmbMemberId.addItem(memberDto.getMembetId());
            }
        } catch (Exception ex) {
            Logger.getLogger(BurrowingView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadSelectedBook() {
        try {
            String bookId = (String) cmbBookId.getSelectedItem();
            BookDto bookDto = BOOK_CONTROLLER.getBookById(bookId);
            if (bookDto != null) {
                lblBookDetails.setText(bookDto.getCategoryId() + " | " + bookDto.getTitle() + " | " + bookDto.getAuthor() + " | " + bookDto.getQty());
            }
        } catch (Exception ex) {
            Logger.getLogger(BurrowingView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadSelectedMember() {
        try {
            String memberId = (String) cmbMemberId.getSelectedItem();
            MemberDto memberDto = MEMBER_CONTROLLER.getMemberbyId(memberId);
            if (memberDto != null) {
                lblMemberDetails.setText(memberDto.getName() + " | " + memberDto.getAddress() + " | " + memberDto.getContactNumber());
            }
        } catch (Exception ex) {
            Logger.getLogger(BurrowingView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadBurrowingId() {
        try {
            String latestId = BURROWING_CONTROLLER.getLatestId();
            if (latestId == null) {
                txtBurrowingId.setText("BU001");
            }else{
                int idNum = Integer.parseInt(latestId.substring(2));
                idNum++;
                String newId = String.format("BU%03d", idNum);
                txtBurrowingId.setText(newId);
            }
        } catch (Exception ex) {
            Logger.getLogger(BurrowingView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
